# Generated by Django 5.1.4 on 2025-01-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='api',
            new_name='Course',
        ),
    ]
