# Generated by Django 5.1.4 on 2025-01-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_course_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='GMT+3', max_length=200),
            preserve_default=False,
        ),
    ]
